import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
import { JotaiProvider } from "@/components/ui/jotai-provider";
import Modal from "@/components/modal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Socialla",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/logo.png",
        href: "/logo.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-[#d4f0f0]/30 via-[#0f9bf6]/5 to-[#ecd5e3]/20`}
      >
        <JotaiProvider>
          <Modal />
          <Toaster />
          {children}
        </JotaiProvider>
      </body>
    </html>
  );
}
